### PR TITLE
HPCC-13297 Replace '-' with '~' for rc build on DEB systems

### PR DESCRIPTION
**Pull request by xwang2713**
This will help deb system to correctly compare the different versions. i.e.
final release version should be greater than rc builds.

@GordonSmith please review

Signed-off-by: xiaoming.wang <xiaoming.wang@lexisnexis.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
Looks fine.

**Comment by GordonSmith** [comment]
@xwang2713 - is this something we should do for IDE as well (or is it only a DEB thing?)

**Comment by richardkchapman** [comment]
DEB and RPM - but I don't think it impacts the IDE as that is only packaged for Windows.

**Comment by xwang2713** [comment]
@GordonSmith Don't need do anything for Windows build which doesn't use build sequence and release information for versioning.

**Pull request merged**
